// Generated by the MSProtoc compiler.  DO NOT EDIT!
// source: MSProtoPublic.proto

#pragma once
#include "MSProtocol/MSPacket.h"

namespace Milesight {
namespace Protocol {


enum MSProtoSortType  
{
  MSProtoSortType_None = 0,
  MSProtoSortType_Asc = 1,
  MSProtoSortType_Desc = 2
};

enum MSProtoNotifyType  
{
  MSProtoNotifyType_Normal = 0,
  MSProtoNotifyType_Changed = 1,
  MSProtoNotifyType_New = 2,
  MSProtoNotifyType_Del = 3
};

enum MSProtoDeviceType  
{
  MSProtoDeviceType_IPC = 0,
  MSProtoDeviceType_NVR = 1
};

enum MSProtoStreamProtocol  
{
  MSProtoStreamProtocol_None = 0,
  MSProtoStreamProtocol_Tcp = 1,
  MSProtoStreamProtocol_Udp = 2,
  MSProtoStreamProtocol_UdpMulticast = 3
};

enum MSProtoDCFactoryType  
{
  MSProtoDCFactoryType_Onvif = 1,
  MSProtoDCFactoryType_RTSP = 2,
  MSProtoDCFactoryType_Milesight = 3
};

enum MSProtoStreamType  
{
  MSProtoStreamType_Main = 0,
  MSProtoStreamType_Sub = 1,
  MSProtoStreamType_Third = 2,
  MSProtoStreamType_Fourth = 3,
  MSProtoStreamType_Fifth = 4
};

enum MSProtoSnapImageType  
{
  MSProtoSnapImageType_JPG = 0,
  MSProtoSnapImageType_PNG = 1,
  MSProtoSnapImageType_BMP = 2
};

enum MSProtoPTZCmd  
{
  MSProtoPTZCmd_None = 0,
  MSProtoPTZCmd_Up = 1,
  MSProtoPTZCmd_Down = 2,
  MSProtoPTZCmd_Left = 3,
  MSProtoPTZCmd_Right = 4,
  MSProtoPTZCmd_UpLeft = 5,
  MSProtoPTZCmd_DownLeft = 6,
  MSProtoPTZCmd_UpRight = 7,
  MSProtoPTZCmd_DownRight = 8,
  MSProtoPTZCmd_AutoScan = 9,
  MSProtoPTZCmd_ZoomIn = 10,
  MSProtoPTZCmd_ZoomOut = 11,
  MSProtoPTZCmd_ZoomAuto = 12,
  MSProtoPTZCmd_FocusNear = 13,
  MSProtoPTZCmd_FocusFar = 14,
  MSProtoPTZCmd_FocusAuto = 15,
  MSProtoPTZCmd_IrisOpen = 16,
  MSProtoPTZCmd_IrisClose = 17,
  MSProtoPTZCmd_IrisAuto = 18,
  MSProtoPTZCmd_LightOn = 19,
  MSProtoPTZCmd_LightOff = 20,
  MSProtoPTZCmd_WiperOn = 21,
  MSProtoPTZCmd_WiperOff = 22,
  MSProtoPTZCmd_AutoHomeOn = 23,
  MSProtoPTZCmd_AutoHomeOff = 24,
  MSProtoPTZCmd_DehumidifyingOn = 25,
  MSProtoPTZCmd_DehumidifyingOff = 26,
  MSProtoPTZCmd_OneTouchPartrolOn = 27,
  MSProtoPTZCmd_OneTouchPartrolOff = 28,
  MSProtoPTZCmd_Initialization = 29
};

enum MSProtoFishEyeInstall  
{
  MSProtoFishEyeInstall_Ceiling = 0,
  MSProtoFishEyeInstall_WallMounting = 1,
  MSProtoFishEyeInstall_Flat = 2
};

enum MSProtoFishEyeDisplay  
{
  MSProtoFishEyeDisplay_1O = 0,
  MSProtoFishEyeDisplay_1P = 1,
  MSProtoFishEyeDisplay_2P = 2,
  MSProtoFishEyeDisplay_4R = 4,
  MSProtoFishEyeDisplay_1O3R = 5,
  MSProtoFishEyeDisplay_1P3R = 6,
  MSProtoFishEyeDisplay_1O1P3R = 7
};

enum MSProtoCameraAlarmType  
{
  MSProtoCameraAlarmType_None = 0,
  MSProtoCameraAlarmType_motion = 1,
  MSProtoCameraAlarmType_mask = 2,
  MSProtoCameraAlarmType_lost = 3,
  MSProtoCameraAlarmType_input = 4
};

enum MSProtoCameraAlarmStatus  
{
  MSProtoCameraAlarmStatus_Starts = 1,
  MSProtoCameraAlarmStatus_Stops = 2,
  MSProtoCameraAlarmStatus_Keep = 3
};

enum MSProtoStreamSpeed  
{
  MSProtoStreamSpeed_Slow_16x = 1,
  MSProtoStreamSpeed_Slow_8x = 2,
  MSProtoStreamSpeed_Slow_4x = 3,
  MSProtoStreamSpeed_Slow_2x = 4,
  MSProtoStreamSpeed_Fast_1x = 5,
  MSProtoStreamSpeed_Fast_2x = 6,
  MSProtoStreamSpeed_Fast_4x = 7,
  MSProtoStreamSpeed_Fast_8x = 8,
  MSProtoStreamSpeed_Fast_16x = 9
};

enum MSProtoEventType  
{
  MSProtoEventType_User = 1,
  MSProtoEventType_System = 2,
  MSProtoEventType_CameraAlarm = 3,
  MSProtoEventType_Trigger = 4,
  MSProtoEventType_Device = 5
};

enum MSProtoEventAction_Device  
{
  MSProtoEventAction_Device_Update = 1000,
  MSProtoEventAction_Device_Del = 1001,
  MSProtoEventAction_Device_Online = 1002,
  MSProtoEventAction_Device_Offline = 1003
};

enum MSProtoEventAction_User  
{
  MSProtoEventAction_User_Add = 2000,
  MSProtoEventAction_User_Del = 2001,
  MSProtoEventAction_User_Mod = 2002,
  MSProtoEventAction_User_Login = 2003,
  MSProtoEventAction_User_Logout = 2004
};

enum MSProtoEventAction_UserRoles  
{
  MSProtoEventAction_UserRoles_Update = 2500,
  MSProtoEventAction_UserRoles_Del = 2501
};

enum MSProtoEventAction_Storage  
{
  MSProtoEventAction_Storage_UpdateDisk = 3000,
  MSProtoEventAction_Storage_UpdateSchedule = 3001,
  MSProtoEventAction_Storage_UpdateDevSetting = 3002,
  MSProtoEventAction_Storage_AddTag = 3003,
  MSProtoEventAction_Storage_DelTag = 3004,
  MSProtoEventAction_Storage_AddExtendDisk = 3005,
  MSProtoEventAction_Storage_DelExtendDisk = 3006
};

enum MSProtoEventRulesSourceStatus  
{
  MSProtoEventRulesSourceStatus_None = 0,
  MSProtoEventRulesSourceStatus_Starts = 1,
  MSProtoEventRulesSourceStatus_Stops = 2,
  MSProtoEventRulesSourceStatus_Course = 3
};

enum MSProtoEventRulesSource  
{
  MSProtoEventRulesSource_None = 0,
  MSProtoEventRulesSource_Server_Notify = 10,
  MSProtoEventRulesSource_Device_Offline = 100,
  MSProtoEventRulesSource_DeviceAlarm = 200,
  MSProtoEventRulesSource_DeviceAlarm_Input = 201,
  MSProtoEventRulesSource_DeviceAlarm_Motion = 202,
  MSProtoEventRulesSource_StorageError = 300,
  MSProtoEventRulesSource_Trigger = 400,
  MSProtoEventRulesSource_GenericEvent = 500,
  MSProtoEventRulesSource_DevIPConflict = 600,
  MSProtoEventRulesSource_NetworkFault = 601,
  MSProtoEventRulesSource_SVRIPConflict = 602,
  MSProtoEventRulesSource_ServerOffline = 700,
  MSProtoEventRulesSource_ServerStart = 701,
  MSProtoEventRulesSource_Activate = 800,
  MSProtoEventRulesSource_Failover = 801
};

enum MSProtoEventRulesAction  
{
  MSProtoEventRulesAction_None = 0,
  MSProtoEventRulesAction_Device_Storage = 100,
  MSProtoEventRulesAction_Device_StorageBookmark = 101,
  MSProtoEventRulesAction_Device_StorageMainStream = 102,
  MSProtoEventRulesAction_Device_PTZ = 200,
  MSProtoEventRulesAction_Device_Alarmoutput = 201,
  MSProtoEventRulesAction_Device_PlayAudio = 202,
  MSProtoEventRulesAction_HTTP = 300,
  MSProtoEventRulesAction_Email = 301,
  MSProtoEventRulesAction_ShowNotify = 302,
  MSProtoEventRulesAction_ShowAlarm = 303,
  MSProtoEventRulesAction_OSD = 304,
  MSProtoEventRulesAction_WriteToLog = 400
};

enum MSProtoRecordType  
{
  MSProtoRecordType_Time = 0,
  MSProtoRecordType_Motion = 1,
  MSProtoRecordType_AlarmIn = 2,
  MSProtoRecordType_Manual = 4,
  MSProtoRecordType_ANR = 8,
  MSProtoRecordType_VCR = 16
};

enum MSProtoTimeZone  
{
  MSProtoTimeZone_UTC_Minus_11_Samoa = 0,
  MSProtoTimeZone_UTC_Minus_10_Cook = 1,
  MSProtoTimeZone_UTC_Minus_10_Polynesia = 2,
  MSProtoTimeZone_UTC_Minus_10_USA = 3,
  MSProtoTimeZone_UTC_Minus_10_USA2 = 4,
  MSProtoTimeZone_UTC_Minus_9_USA = 5,
  MSProtoTimeZone_UTC_Minus_8_CAN = 6,
  MSProtoTimeZone_UTC_Minus_8_MEX = 7,
  MSProtoTimeZone_UTC_Minus_8_USA = 8,
  MSProtoTimeZone_UTC_Minus_7_CAN = 9,
  MSProtoTimeZone_UTC_Minus_7_MEX = 10,
  MSProtoTimeZone_UTC_Minus_7_USA = 11,
  MSProtoTimeZone_UTC_Minus_6_CAN = 12,
  MSProtoTimeZone_UTC_Minus_6_CHL = 13,
  MSProtoTimeZone_UTC_Minus_6_MEX = 14,
  MSProtoTimeZone_UTC_Minus_6_USA = 15,
  MSProtoTimeZone_UTC_Minus_5_BHS = 16,
  MSProtoTimeZone_UTC_Minus_5_BRA = 17,
  MSProtoTimeZone_UTC_Minus_5_CAN = 18,
  MSProtoTimeZone_UTC_Minus_5_CUB = 19,
  MSProtoTimeZone_UTC_Minus_5_USA = 20,
  MSProtoTimeZone_UTC_Minus_4_VEN = 21,
  MSProtoTimeZone_UTC_Minus_4_CAN = 22,
  MSProtoTimeZone_UTC_Minus_4_CHL = 23,
  MSProtoTimeZone_UTC_Minus_4_PRY = 24,
  MSProtoTimeZone_UTC_Minus_4_TTB = 25,
  MSProtoTimeZone_UTC_Minus_4_BMU = 26,
  MSProtoTimeZone_UTC_Minus_4_FLK = 27,
  MSProtoTimeZone_UTC_Minus_3_30_CAN = 28,
  MSProtoTimeZone_UTC_Minus_3_ARG = 29,
  MSProtoTimeZone_UTC_Minus_3_BRA2 = 30,
  MSProtoTimeZone_UTC_Minus_3_BRA1 = 31,
  MSProtoTimeZone_UTC_Minus_3_GRL = 32,
  MSProtoTimeZone_UTC_Minus_2_BRA = 33,
  MSProtoTimeZone_UTC_Minus_1_PRT = 34,
  MSProtoTimeZone_UTC0_FRO = 35,
  MSProtoTimeZone_UTC0_IRL = 36,
  MSProtoTimeZone_UTC0_PRT = 37,
  MSProtoTimeZone_UTC0_ESP = 38,
  MSProtoTimeZone_UTC0_GBR = 39,
  MSProtoTimeZone_UTC1_ALB = 40,
  MSProtoTimeZone_UTC1_AUT = 41,
  MSProtoTimeZone_UTC1_BEL = 42,
  MSProtoTimeZone_UTC1_HRV = 43,
  MSProtoTimeZone_UTC1_CZE = 44,
  MSProtoTimeZone_UTC1_DNK = 45,
  MSProtoTimeZone_UTC1_FRA = 46,
  MSProtoTimeZone_UTC1_GER = 47,
  MSProtoTimeZone_UTC1_HUN = 48,
  MSProtoTimeZone_UTC1_ITA = 49,
  MSProtoTimeZone_UTC1_LUX = 50,
  MSProtoTimeZone_UTC1_MAK = 51,
  MSProtoTimeZone_UTC1_NAM = 52,
  MSProtoTimeZone_UTC1_NLD = 53,
  MSProtoTimeZone_UTC1_NGR = 54,
  MSProtoTimeZone_UTC1_NOR = 55,
  MSProtoTimeZone_UTC1_POL = 56,
  MSProtoTimeZone_UTC1_YUG = 57,
  MSProtoTimeZone_UTC1_SVK = 58,
  MSProtoTimeZone_UTC1_SVN = 59,
  MSProtoTimeZone_UTC1_ESP = 60,
  MSProtoTimeZone_UTC1_SWE = 61,
  MSProtoTimeZone_UTC1_CHE = 62,
  MSProtoTimeZone_UTC1_GIB = 63,
  MSProtoTimeZone_UTC1_WAT = 64,
  MSProtoTimeZone_UTC2_BGR = 65,
  MSProtoTimeZone_UTC2_CYP = 66,
  MSProtoTimeZone_UTC2_CAT = 67,
  MSProtoTimeZone_UTC2_EGY = 68,
  MSProtoTimeZone_UTC2_EST = 69,
  MSProtoTimeZone_UTC2_FIN = 70,
  MSProtoTimeZone_UTC2_GAZ = 71,
  MSProtoTimeZone_UTC2_GRC = 72,
  MSProtoTimeZone_UTC2_ISR = 73,
  MSProtoTimeZone_UTC2_JOR = 74,
  MSProtoTimeZone_UTC2_LVA = 75,
  MSProtoTimeZone_UTC2_LBN = 76,
  MSProtoTimeZone_UTC2_MDA = 77,
  MSProtoTimeZone_UTC2_PAL = 78,
  MSProtoTimeZone_UTC2_ROU = 79,
  MSProtoTimeZone_UTC2_RUS = 80,
  MSProtoTimeZone_UTC2_SAC = 81,
  MSProtoTimeZone_UTC2_SYR = 82,
  MSProtoTimeZone_UTC2_UKR = 83,
  MSProtoTimeZone_UTC3_BLR = 84,
  MSProtoTimeZone_UTC3_EAT = 85,
  MSProtoTimeZone_UTC3_IRQ = 86,
  MSProtoTimeZone_UTC3_AST = 87,
  MSProtoTimeZone_UTC3_QTR = 88,
  MSProtoTimeZone_UTC3_RUS = 89,
  MSProtoTimeZone_UTC3_KSA = 90,
  MSProtoTimeZone_UTC3_TUR = 91,
  MSProtoTimeZone_UTC3_30_IRN = 92,
  MSProtoTimeZone_UTC4_ARM = 93,
  MSProtoTimeZone_UTC4_AZE = 94,
  MSProtoTimeZone_UTC4_GEO = 95,
  MSProtoTimeZone_UTC4_RUS = 96,
  MSProtoTimeZone_UTC4_UAE = 97,
  MSProtoTimeZone_UTC5_KAZ1 = 98,
  MSProtoTimeZone_UTC5_KAZ = 99,
  MSProtoTimeZone_UTC5_PAK = 100,
  MSProtoTimeZone_UTC5_RUS = 101,
  MSProtoTimeZone_UTC5_30_IND = 102,
  MSProtoTimeZone_UTC5_45_NPL = 103,
  MSProtoTimeZone_UTC6_KAZ = 104,
  MSProtoTimeZone_UTC6_KGZ = 105,
  MSProtoTimeZone_UTC6_RUS = 106,
  MSProtoTimeZone_UTC6_30_MMT = 107,
  MSProtoTimeZone_UTC7_RUS = 108,
  MSProtoTimeZone_UTC7_THA = 109,
  MSProtoTimeZone_UTC7_VTN = 110,
  MSProtoTimeZone_UTC8_AUS = 111,
  MSProtoTimeZone_UTC8_CHN = 112,
  MSProtoTimeZone_UTC8_SGP = 113,
  MSProtoTimeZone_UTC9_JPN = 114,
  MSProtoTimeZone_UTC9_KOR = 115,
  MSProtoTimeZone_UTC9_30_AUS = 116,
  MSProtoTimeZone_UTC9_30_AUS2 = 117,
  MSProtoTimeZone_UTC10_AUS = 118,
  MSProtoTimeZone_UTC10_AUS2 = 119,
  MSProtoTimeZone_UTC10_AUS3 = 120,
  MSProtoTimeZone_UTC10_RUS = 121,
  MSProtoTimeZone_UTC10_30_AUS = 122,
  MSProtoTimeZone_UTC11_NCL = 123,
  MSProtoTimeZone_UTC12_NZL = 124,
  MSProtoTimeZone_UTC12_RUS = 125,
  MSProtoTimeZone_UTC12_45_NZL = 126,
  MSProtoTimeZone_UTC13_TON = 127
};

// ===================================================================

struct MSProtoDeviceId :public MSPacket
{
 public:
	// filed devid Required !!
	uint64_t devid=0;

	bool operator==(const MSProtoDeviceId& _opt_msg_) const
	{
		return devid == _opt_msg_.devid;
	}

private:
	const char* getTypeName()const{return "MSProtoDeviceId";}
};


}
}
